baseurl: ''
title: Ninoshka &ndash; Fashion with a conscience
description: Ninoshka Alvares-Delaney is an Indian fashion designer from Goa who believes in Fashion with a conscience.
exclude: ['README.md', 'ninoshka.sublime-workspace', '.jekyll-metadata']
markdown: redcarpet
name: Ninoshka &ndash; Fashion with a conscience
permalink: /:categories/:title/